'''uiDesign module for Data/Ia Dev Script -- Nicolas Autexier -- contact = nicolas.atx@gmx.fr '''
# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import ress_rc


class Ui_MoviesPredictor(object):
    
    def setupUi(self, MoviesPredictor):
        MoviesPredictor.setObjectName("MoviesPredictor")
        MoviesPredictor.resize(910, 727)
        MoviesPredictor.setMinimumSize(QtCore.QSize(910, 727))
        MoviesPredictor.setMaximumSize(QtCore.QSize(1200, 800))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 80, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 120, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 100, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 40, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 53, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 80, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 167, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 80, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 120, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 100, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 40, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 53, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 80, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 167, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 40, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 80, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 120, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 100, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 40, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 53, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 40, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(38, 40, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 80, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 80, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 80, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MoviesPredictor.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(20)
        MoviesPredictor.setFont(font)
        MoviesPredictor.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/smalicon/kisspng.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MoviesPredictor.setWindowIcon(icon)
        MoviesPredictor.setLayoutDirection(QtCore.Qt.LeftToRight)
        MoviesPredictor.setAutoFillBackground(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(MoviesPredictor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Title = QtWidgets.QTextEdit(MoviesPredictor)
        self.Title.setEnabled(True)
        self.Title.setMinimumSize(QtCore.QSize(490, 310))
        self.Title.setMaximumSize(QtCore.QSize(490, 310))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.gridLayout_2.addWidget(self.Title, 2, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 12, 2, 1, 3)
        self.lineEdit_2 = QtWidgets.QLineEdit(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 10, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 14, 0, 1, 1)
        self.Result = QtWidgets.QLabel(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Result.setFont(font)
        self.Result.setToolTipDuration(-6)
        self.Result.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.Result.setObjectName("Result")
        self.gridLayout_2.addWidget(self.Result, 8, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 12, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 13, 2, 1, 3)
        self.lineEdit = QtWidgets.QLineEdit(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 11, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 10, 2, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 15, 0, 1, 2)
        self.lineEdit_11 = QtWidgets.QLineEdit(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 14, 2, 1, 3)
        self.lineEdit_5 = QtWidgets.QLineEdit(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 13, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 15, 2, 1, 2)
        self.lineEdit_12 = QtWidgets.QLineEdit(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setDragEnabled(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 16, 2, 1, 3)
        self.lineEdit_8 = QtWidgets.QLineEdit(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 11, 2, 1, 3)
        self.lineEdit_3 = QtWidgets.QLineEdit(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 8, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.radioButton.setFont(font)
        self.radioButton.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 16, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(MoviesPredictor)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setDefault(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 17, 0, 1, 1)
        self.PredButton = QtWidgets.QPushButton(MoviesPredictor)
        self.PredButton.setMinimumSize(QtCore.QSize(370, 300))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.PredButton.setFont(font)
        self.PredButton.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.PredButton.setStyleSheet("font: 14pt \"Cooper Black\";\n"
        "text-decoration: underline;")
        self.PredButton.setAutoDefault(False)
        self.PredButton.setDefault(True)
        self.PredButton.setObjectName("PredButton")
        self.gridLayout_2.addWidget(self.PredButton, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 2, 1, 1)

        self.retranslateUi(MoviesPredictor)
        QtCore.QMetaObject.connectSlotsByName(MoviesPredictor)

    def retranslateUi(self, MoviesPredictor):
        _translate = QtCore.QCoreApplication.translate
        MoviesPredictor.setWindowTitle(_translate("MoviesPredictor", "Movies Predictor"))
        self.Title.setHtml(_translate("MoviesPredictor", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'Cooper Black\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/logo/10501.png\" /></p></body></html>"))
        self.lineEdit_9.setText(_translate("MoviesPredictor", "Enter Produceur"))
        self.lineEdit_2.setText(_translate("MoviesPredictor", "Enter Synopsis"))
        self.lineEdit_6.setText(_translate("MoviesPredictor", "Enter Release date"))
        self.Result.setText(_translate("MoviesPredictor", "                    0.5"))
        self.lineEdit_4.setText(_translate("MoviesPredictor", "Enter Genre"))
        self.lineEdit_10.setText(_translate("MoviesPredictor", "Enter Country"))
        self.lineEdit.setText(_translate("MoviesPredictor", "Enter Rating"))
        self.lineEdit_7.setText(_translate("MoviesPredictor", "Enter Director"))
        self.lineEdit_11.setText(_translate("MoviesPredictor", "Enter Writer"))
        self.lineEdit_5.setText(_translate("MoviesPredictor", "Enter Duration"))
        self.lineEdit_12.setText(_translate("MoviesPredictor", "Name of file.csv "))
        self.lineEdit_8.setText(_translate("MoviesPredictor", "Enter People"))
        self.lineEdit_3.setText(_translate("MoviesPredictor", "Enter Title"))
        self.radioButton.setText(_translate("MoviesPredictor", "Check For Multiple Predictions"))
        self.pushButton.setText(_translate("MoviesPredictor", "Show Help !!"))
        self.PredButton.setText(_translate("MoviesPredictor", "Make Prediction"))


        self.PredButton.clicked.connect(self.singlePrediction)
        self.pushButton.clicked.connect(self.showHelp)

    def singlePrediction(self):

        _translate = QtCore.QCoreApplication.translate
        self.Result.setText(_translate("MoviesPredictor", "Working on prediction"))

        model_id = "model/5e09292b3514cd286f01ece4"
        mod = "model"

        if self.radioButton.isChecked() != True :
            from biglearn import singlePredProd as SP

            array_to_send = [self.lineEdit_3.text(),self.lineEdit_2.text(),self.lineEdit.text(),self.lineEdit_4.text(),self.lineEdit_5.text(),
                            self.lineEdit_6.text(),self.lineEdit_7.text(),self.lineEdit_8.text(),self.lineEdit_9.text(),self.lineEdit_10.text(),
                            self.lineEdit_11.text()]

            pred_value = SP.singlePred(model_id,mod,array_to_send)

            self.Result.setText(_translate("MoviesPredictor", f"{round(pred_value,2)}"))
        else :
            from biglearn import predmeth1Kagg as MP
            filetest = self.lineEdit_12.text()
            export = "TheMoviesPrediction.csv"
            MP(model_id,mod,filetest,export)
            self.Result.setText(_translate("MoviesPredictor", "Prediction Done !"))


    def showHelp(self):

        msg_text = """
        Simple prediction: fill all the fields, in English (except the title, it can be in Fr). The lists of people must be separated by commas (brad pitt, penèlope cruz, ...)

        Multiple prediction: ticked the box, note the name of the.csv file in the box next to it. The file should be placed in the root of the folder. it must contain all the columns named for simple prediction.  There can be several movies without limit but also 1. The prediction file will be generated in the PredFiles folder in .csv format.
        
        For more information read the readme files, if one day i make a good one :)

        Thank's for trying this app & plz give any feedback @ """

        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Information")
        msg.setText(f"{msg_text}")
        msg.setIcon(QtWidgets.QMessageBox.Information)

        msg.exec_()


#  if __name__ == "__main__":

app = QtWidgets.QApplication(sys.argv)
MoviesPredictor = QtWidgets.QWidget()
ui = Ui_MoviesPredictor()
ui.setupUi(MoviesPredictor)
MoviesPredictor.show()
sys.exit(app.exec_())
